config/routes.rb
Rails.application.routes.draw do
  post 'flats/search', to: 'flats#search', as: "search_flats"
  resources :flats
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  # GET /flats
  # GET /flats.json
  def index
    @flats = Flat.all
  end

  # GET /flats/1
  # GET /flats/1.json
  def show
  end

  # GET /flats/new
  def new
    @flat = Flat.new
  end

  # GET /flats/1/edit
  def edit
  end

  # POST /flats
  # POST /flats.json
  def create
    @flat = Flat.new(flat_params)

    respond_to do |format|
      if @flat.save
        format.html { redirect_to @flat, notice: 'Flat was successfully created.' }
        format.json { render :show, status: :created, location: @flat }
      else
        format.html { render :new }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flats/1
  # PATCH/PUT /flats/1.json
  def update
    respond_to do |format|
      if @flat.update(flat_params)
        format.html { redirect_to @flat, notice: 'Flat was successfully updated.' }
        format.json { render :show, status: :ok, location: @flat }
      else
        format.html { render :edit }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flats/1
  # DELETE /flats/1.json
  def destroy
    @flat.destroy
    respond_to do |format|
      format.html { redirect_to flats_url, notice: 'Flat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flat
      @flat = Flat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def flat_params
      params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
  def magic_number(flats)
    flats.map {|flat| (rand() * 20).to_i }
  end
end

app/views/flats/_form.html.erb
<%= form_with(model: flat, local: true) do |form| %>
  <% if flat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flat.errors.count, "error") %> prohibited this flat from being saved:</h2>

      <ul>
        <% flat.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price_per_night %>
    <%= form.number_field :price_per_night %>
  </div>

  <div class="field">
    <%= form.label :number_of_guests %>
    <%= form.number_field :number_of_guests %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/flats/edit.html.erb
<h1>Editing Flat</h1>

<%= render 'form', flat: @flat %>

<%= link_to 'Show', @flat %> |
<%= link_to 'Back', flats_path %>

app/views/flats/index.html.erb
<p id="notice"><%= notice %></p>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">Simple Airbnb</a>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="ml-auto flex">
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" name="query" type="search" placeholder="Search" aria-label="Search" value="">
            <button class="btn btn-outline-success my-2 my-sm-2" type="submit">Search</button>
          </form>
          <a class="btn btn-outline-primary my-2 my-sm-2 ml-2" href="/flats/new">Add Flat</a>
        </div>
      </div>
    </nav>

    <div class="container mt-3">
  <div class="row">
    <div class="col-12">
      <h1>All our Flats</h1>
    </div>
  </div>

<!-- <table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Description</th>
      <th>Price per night</th>
      <th>Number of guests</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flats.each do |flat| %>
      <tr>
        <td><%= flat.name %></td>
        <td><%= flat.address %></td>
        <td><%= flat.description %></td>
        <td><%= flat.price_per_night %></td>
        <td><%= flat.number_of_guests %></td>
        <td><%= link_to 'Show', flat %></td>
        <td><%= link_to 'Edit', edit_flat_path(flat) %></td>
        <td><%= link_to 'Destroy', flat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br> -->


<div class="row">
  <% @flats.each do |flat| %>
      <div class="col-4">
        <div class="flat-card">
          <div class="flat-card-image" style="background-image: url('https://picsum.photos/300/200?image=<%= (rand() * 20).to_i %>')">
          </div>
            <div class="flat-card-content">
              <div class="flat-card-title">
                <h5 id="card-title"><%= flat.name %></h5>
              </div>
              <p><%= flat.address %></p>
                <div class="flex">
                <div class="flex">
                  <i class="fas fa-user-friends">    <%= flat.number_of_guests %></i>
                </div>
                <div class="flex ml-3">
                  <i class="fas fa-euro-sign">    <%= flat.price_per_night %></i>
                </div>
              </div>
            </div>
        </div>
      </div>
    <% end %>
  </div>

<!--

ONDE EU PAREI: TENTANDO FAZER OS LINKS DE EDIT E DELETE FUNCIONAREM COM O ESTILO:
<a class="ml-3 text-warning" href="/flats/3358/edit">Edit</a>
<a data-confirm="Are you sure?" class="ml-3 text-danger" rel="nofollow" data-method="delete" href="/flats/3358">Remove</a>

<%= link_to 'New Flat', new_flat_path %>
-->

app/views/flats/new.html.erb
<h1>New Flat</h1>

<%= render 'form', flat: @flat %>

<%= link_to 'Back', flats_path %>

app/views/flats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @flat.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @flat.address %>
</p>

<p>
  <strong>Description:</strong>
  <%= @flat.description %>
</p>

<p>
  <strong>Price per night:</strong>
  <%= @flat.price_per_night %>
</p>

<p>
  <strong>Number of guests:</strong>
  <%= @flat.number_of_guests %>
</p>

<%= link_to 'Edit', edit_flat_path(@flat) %> |
<%= link_to 'Back', flats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  </head>

  <body>
    <%= yield %>
  </body>
</html>